import './globals.css'
import { Inter } from 'next/font/google'
import Nav from "./auth/Nav"
import { Roboto } from 'next/font/google'
import QueryWrapper from "./auth/QueryWrapper"


const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["400", "700"], 
  variable: "--font-roboto",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      {

      }
    <head />
      <body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable} bg-pink-100`}>
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}


/**export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">{}
    <head />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
**/